language: go
go:
  - 1.9.x
  - 1.10.x
sudo: false
install:
  - go get -d -t -v ./...
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
